FUNCTION_TYPES = {
    "linear":{
        "k":float,
        "b":float
    },
    "quadratic":{
        "a":float,
        "b":float,
        "c":float,
    },
    "cubic":{
        "a":float,
        "b":float,
        "c":float,
        "d":float,
    },
    "exponential":{
        "a":float,
        "lambda_":float
    },
    "logarithm":{
        "k":float,
        "a":int,
        "b":int
    },
    "sinus":{
        "a":float,
        "omega":float
    },
    "cosine":{
        "a":float,
        "omega":float
    },
    "tangent":{
        "a":float,
        "omega":float
    },
    "cotangent":{
        "a":float,
        "omega":float
    }
}